### ISSUE TITLE
Issues with "emojis of author" and "emoji detail" views on mobile

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#100]
Hi @felixhaeberle, I have trouble with the emojis of author" and "emoji detail" views on mobile (Safari and Firefox). Hard to explain ... basically

- "emojis of author" link are only working if opened in a new tap
- "emoji detail" link is only working once

please see Video:
[RPReplay_Final1585638265.MP4.zip](https://github.com/hfg-gmuend/openmoji-website/files/4407299/RPReplay_Final1585638265.MP4.zip)

This is quite bad ... as the core feature of the website is too browse the emojis ... and it is live.

Could you have a look on the issues tagged with [bug](https://github.com/hfg-gmuend/openmoji-website/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and double check everything?

**Comment by felixhaeberle** [comment]
I'll care about this today.

**Comment by felixhaeberle** [comment]
I found a solution for the bug and will commit it tomorrow after testing it 👍

**Comment by felixhaeberle** [comment]
@b-g This is already fixed by the last PR. 🚢

**Comment by b-g** [comment]
@felixhaeberle Nope! Still the same bug :(

Please:
- investigate and commit potential solutions directly to Master
- test via the staging (everything in Master is automatically stagged) https://hfg-gmuend.github.io/openmoji-website/ on a mobile phone

**Comment by felixhaeberle** [comment]
Mmh okay, this one is really strange, I'll look it up tonight.

**Comment by b-g** [comment]
@felixhaeberle Ping :) Any news?

**Comment by felixhaeberle** [comment]
Yes! I'll have a look on this today for sure :)

**Comment by felixhaeberle** [comment]
This one was really tricky! :)
Tried to fix it with JS but had no luck, setting a Cache-Control header should fix it I guess based on my trouble shooting :)
@b-g Could you fix that?

See https://stackoverflow.com/questions/7248111/how-to-prevent-content-being-displayed-from-back-forward-cache-in-firefox

> If you set `Cache-Control: "no-cache, no-store, must-revalidate"` to http headers the page won't be cached in back-forward cache. Firefox also considers event handlers on beforeunload event as a signal to not store page in BFC, but Safari ignores such handlers, so it's better to set correct http headers to indicate the nature of the page content (cacheable or variable)

**Comment by b-g** [comment]
@felixhaeberle Many thanks for this! Could you please add the settings to https://github.com/hfg-gmuend/openmoji-website/blob/master/.htaccess ... you can deploy/test by merging to branch production. It will go online within a few mins. See the Github Actions tab for the status. 

I think it makes more sense if you could do this ... as you already spent time on this. Otherwise let me know ...

**Comment by b-g** [comment]
@felixhaeberle at least on my end the entire website feels really really slow. Is this just me? Or if not ... is there a smarter way to deal with the headers and caching?

**Comment by b-g** [comment]
e.g. all images cached for a month
```
<filesMatch ".(ico|svg|jpg|jpeg|png|gif|css)$">
    Header set Cache-Control "max-age=2628000, public"
</filesMatch>
```

**Comment by felixhaeberle** [comment]
yes, we could try that and see what's the outcome! caching the pictures and css shouldn't be a problem.

**Comment by felixhaeberle** [comment]
@b-g I did the adjustments like you described above. I'm going to test it on some devices soon. Let's see how we improved.

**Comment by b-g** [comment]
Great! Fingers crossed :)

**Comment by b-g** [comment]
Closing this issue! Fixed! Yay!! @felixhaeberle 🙏
