### ISSUE TITLE
Add download sizes

### ISSUE THREAD

**Issue by carlinmack** [hfg-gmuend/openmoji-website#116]
![image](https://user-images.githubusercontent.com/6676843/82124743-fae91f00-976e-11ea-8f48-546c4304c610.png)

On Chrome for me it starts downloading when you click so I think it would be better to warn people. Should I make a PR?

**Comment by b-g** [comment]
Yes ... but then we would allways have to update this. A pain to maintain. Could we either not add the infos or be really vague "< 5 MB" and "~ 30 MB"? My vote would go to not add the infos.

**Comment by carlinmack** [comment]
that's fine 👍
