### ISSUE TITLE
Refactor url parameters to be using '#' instead of '?'

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#13]
We would like to use this Github repo in the future for hosting the website ...

Problem: 
Any url with a '?' yields 404 e.g.
https://hfg-gmuend.github.io/library.html?emoji=1F4E6 

Fix:
Refactor url parameters to be using '#' instead of '?'

**Comment by b-g** [comment]
@PaulRaschke Thanks! Works now with github: https://hfg-gmuend.github.io/openmoji-website/index.html ... Just the emoji links in the landing header are still broken. Plz fix.

**Comment by PaulRaschke** [comment]
Hi @b-g,

I wasn't aware of the broken links in the index page. I will fix it asap.
It also seems like a '?' in the url isn't a problem. I tested it and both '?' and '#' seem to work fine. Therefore I would propose to move back to using '?' instead of '#'.

**Comment by b-g** [comment]
Hi @PaulRaschke,

Thanks.

> It also seems like a '?' in the url isn't a problem. I tested it and both '?' and '#' seem to work fine. 
> Therefore I would propose to move back to using '?' instead of '#'.

I would vote to stay with **`#`** as `?` implies IMO a server side query, which we don't do. Hence I believe using `#` is more correct. Can you live with it as well?
