### ISSUE TITLE
Review May 7

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#27]
Review of https://hfg-gmuend.github.io/openmoji-website/

- [x] fix broken imprint #23 

- [x] fix missing github icon in header 
![2019-05-07 at 06 08](https://user-images.githubusercontent.com/480224/57271154-b1132680-708e-11e9-863e-1be4ff9c5a73.png)

- [x] fix broken menu links in header and use relative paths only. The menu links should work on local host and with github hosting (hfg-gmuend.github.io/openmoji-website) 
![2019-05-07 at 06 10](https://user-images.githubusercontent.com/480224/57271231-f899b280-708e-11e9-88e0-4c50b7552548.png)

- [x] find the two "Multi-channels" and "Unicode Version 12.0" with this content too big. Please get rid of the section in terms of layout and integrate the "Unicode Version 12.0" point into the other ones (below headline)

- [x] make both headlines/titles wider, break in two lines on a big screen. (also try two lines for "Special Interest Categories for Technologies and IX/UX/IoT Design")
![2019-05-07 at 06 24](https://user-images.githubusercontent.com/480224/57271762-09e3be80-7091-11e9-8d46-a7d8dd929540.png)

- [x] content "bullet points" under headline: 
1. Free to use
2. 3000+ Emojis
3. Unicode Emoji v12
4. Consistent
5. Colored/Outlined
6. Skintones
7. 250+ Flags (From Andorra to Zimbabwe to Pirates)
8. Special Interest Categories
9. Handcrafted

**Comment by b-g** [comment]
@jodunkel Many thanks + Great! Just ...

- [ ] imprint still broken e.g. go to samples. Plz fix them all.
- [ ] fix broken menu links in header and use relative paths only. Is still partly broken e.g. Home > go to "Samples" > click "Participate" ... please carefully check all the pages. Also for the "OpenMoji" home menu item don't link to "index.html" (also the case from the "Samples" page)
- [ ] Could you tweak the sizes of emoji to make them look visually equally important?
![2019-05-10 at 11 29](https://user-images.githubusercontent.com/480224/57517392-07929600-7317-11e9-8344-dbd2eecbb898.png)

**Comment by jodunkel** [comment]
Hi Bene, 
there's a cache problem on the sample page caused by Github. I don't know why, but in the master file the problems are already fixed. They are only published wrong with Github. I think Github has a problem and it's not the website. So the first two points should be done already and the rest I do now.

**Comment by Sam0711er** [comment]
Can confirm. Github.io is having a weird caching issue. Issues don't appear outside of github.io. Maybe reinitializing helps?

**Comment by b-g** [comment]
Did reinitialize the github hosting ... seems not fully to resolve it. Closing the issue. We host the production site somewhere else anyway.
