### ISSUE TITLE
No flags in black and white

### ISSUE THREAD

**Issue by jodunkel** [hfg-gmuend/openmoji-website#36]

**Comment by jodunkel** [comment]
<img width="920" alt="Bildschirmfoto 2019-05-13 um 17 51 46" src="https://user-images.githubusercontent.com/35904825/57635688-ee544880-75a7-11e9-866e-5e2a85b55fb9.png">

**Comment by b-g** [comment]
Thanks for reporting. We are aware of this ... there are simply no "black only" flags. Ans as we din't have the capacity to create a special feature for this on the website ... I'm afraid we have to live with it. I don't have time to improve it. Closed.
