### ISSUE TITLE
Feedback Mar 1

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#4]
Hi @PaulRaschke, many thanks for this!! Here is my feedback:

Landing/Header
* header, emojis should be slightly bigger (e.g. 125% or give me pointer where I can tweak the size)
* header, every emoji should be clickable and link to the emoji detail view
* sticky nav, can you hide the nav until user has scrolled to it? Or at least hide the search field in the nav area until the user has scrolled down. Looks strange to have the big search field (header) and small search field (nav) visible at the same time

Landing/Explore
* Every emoji should be clickable and link to the emoji detail view
* Can you stop the jumping automatically to the categories once the user has clicked on one? Kind of strange to loose the focus on a category after you deliberately decide on one.
* UI Design, please fix blue line and center icons in relation to title better
![2018-03-01 at 09 12](https://user-images.githubusercontent.com/480224/36833916-4cc2895c-1d31-11e8-9ed4-c825fa831520.png)
* Size of button should be way bigger. Please double.
![2018-03-01 at 09 20](https://user-images.githubusercontent.com/480224/36834079-f3b1806a-1d31-11e8-8f02-9520db15e5cc.png)

Nav
* Arrow in download button ... use plain css for this, no need for an icon. See [Howto - CSS Arrows](https://www.w3schools.com/howto/howto_css_arrows.asp) 
* Get OpenMojis button, please increase width to align with options menu
![2018-03-01 at 09 17](https://user-images.githubusercontent.com/480224/36834003-a9d5395a-1d31-11e8-8d2d-23f82b6defff.png)

Footer
* Change link in footer from "legal" to "Imprint"
* Can we get nicer styled scroll bars in the modal?
* I can confirm that the share on twitter link works
* Yes the email icon doesn't fit will ask Daniel (Utz) to make one

Library
* Please add in title "Author: Sofie Ascherl" for queries like this /library.html?author=Sofie%20Ascherl
![2018-03-01 at 09 24](https://user-images.githubusercontent.com/480224/36834272-a7bd4198-1d32-11e8-90b3-b35d3d05ceb1.png)
* Detail view, make everything clickable and link to our related searches. Unicode link to http://www.decodeunicode.org/en/u+1F42A
![2018-03-01 at 09 27](https://user-images.githubusercontent.com/480224/36835352-34e95fae-1d36-11e8-9c13-be3076b4b3b4.png)
* decrease the height of the white space underneath the title to have more usable scape to display the results
![2018-03-01 at 09 53](https://user-images.githubusercontent.com/480224/36835454-91c8d5b0-1d36-11e8-862b-e60ad8b267bc.png)

About
* Add underneath the name the "teams" ... see layout for the infos
![2018-03-01 at 09 58](https://user-images.githubusercontent.com/480224/36835698-5ed62aa8-1d37-11e8-8266-e24ba5aae5e2.png)

**Comment by b-g** [comment]
@PaulRaschke Please ping me once this done ... so that I can have a look and review. Thanks!

**Comment by PaulRaschke** [comment]
@b-g I already did a commit with changes according to your feedback

**Comment by b-g** [comment]
@PaulRaschke Ok + Great! Please ping me once you are done with everything (all open issues) ... so that I can have a look. Thanks!

**Comment by b-g** [comment]
@PaulRaschke Just reviewed everything from this issue ... all good, just found this last one. Please fix the icon alignment in About ... and close the issue afterwards. Cheers!

![2018-04-06 at 11 28](https://user-images.githubusercontent.com/480224/38414080-ccb64798-398d-11e8-8606-08825d488e2b.png)
