### ISSUE TITLE
Website looks mega horrible on mobile

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#41]
Website looks mega horrible on mobile :( Part of the problem is that you even can't have it 100% on your mobile.

@jodunkel (or anyone else) any chance to gently improve this e.g. show the website as on desktop or at least style the landing site for mobile?

![IMG_C341D7939476-1](https://user-images.githubusercontent.com/480224/57758700-97aa5400-76f8-11e9-9b1b-a5358b90a712.jpeg)

**Comment by b-g** [comment]
Hi @felixhaeberle, that would be mega!! 🙏

**Comment by felixhaeberle** [comment]
I think there is space for improvement in some cases, but in order of this improvement the focus will be to align things which doesn't fit next to each other beneath each other. In some follow-up issues we could target the library section (especially) and the other sections which needs a bit more work in case of the menu sidebar. If anybody has a nice design improvement for those sidebars in mind, that would be very helpful!

**Comment by b-g** [comment]
@felixhaeberle see this?

https://github.com/hfg-gmuend/openmoji-website/issues/14
-> https://www.figma.com/file/IPDkZy9bolQiXRGGnzIVHDDD/openmoji_website_v2

**Comment by felixhaeberle** [comment]
It seems like it's a lot of work, but at least I'm halfway through. Major styling parts of the site had to be rewritten in order to establish a responsive behavior. I'll try to provide a first stable version soon. 🌟 

Preview of my commit history (what's done already).
<img width="764" alt="Screenshot 2019-09-18 12 04 50" src="https://user-images.githubusercontent.com/34959078/65139746-6ecefe00-da0d-11e9-988f-b62046da2e00.png">

**Comment by b-g** [comment]
Hi @felixhaeberle, Wow! That looks like a lot of good work! Much looking forward to see it land here!!! Also happy to give work in progress feedback if helpful! THANKS!

**Comment by felixhaeberle** [comment]
You're welcome! I'll rework the header section on mobile and after that, we could merge the first part of the responsive remake to have the front-page correctly aligned. In addition, it would be cool to open some follow-up issues to tackle the behavior of the other sites and to add some improvements. 

Speaking of improvements, I have plans to integrate postcss/autoprefixer (for greater browser support) into our css build step and do some accessibility improvements (mainly targeting the HTML).

But for now, header. :)

**Comment by b-g** [comment]
Great! Ping me here, or open up a new issue if there is something you would like to share / discuss / feedback. Looking forward!

**Comment by felixhaeberle** [comment]
see #46
