### ISSUE TITLE
Add Github Action to deploy production branch automatically via FTP

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#51]
@PaulRaschke as discussed :)

**Comment by PaulRaschke** [comment]
I added the action with https://github.com/hfg-gmuend/openmoji-website/commit/d1a120fd0337eb69f09db114e250698f0abfaa13. Unfortunately the action doesn't work currently, because the hostname can't be resolved. It seems that FTPS is defined as protocol in the hostname, which conflicts with the definition of the action where SFTP is set. Does the server support SFTP? I will change the protocol used by the action if it doesn't.

**Comment by b-g** [comment]
@PaulRaschke for the remote download of the png files issue ... could you write a proxy e.g. `download-from-github.php` (the webserver has php)? It is a bit confusing that suddenly the PNG button yields e.g. https://github.com/hfg-gmuend/openmoji/raw/master/color/618x618/1F91C.png.

```php
$file_name = $_GET['filename'];
$file_url = 'http://path_to_audio_folder.com/' . $file_name;
header('Content-Type: application/octet-stream');
header("Content-Transfer-Encoding: Binary"); 
header("Content-disposition: attachment; filename=\"".$file_name."\""); 
readfile($file_url);
exit;
```

https://stackoverflow.com/questions/36462985/php-script-to-download-files-from-a-remote-url-to-the-users-computer-directly

**Comment by b-g** [comment]
Hi @PaulRaschke, is the `.git`folder bug fixed? Also please merge production with master so that the Github Action is also part of Master. Thanks! Happy to close the issue afterwards ...

**Comment by PaulRaschke** [comment]
Hi @b_g,

i found a solution for the .git directory bug, but forgot to push it. My bad.
I'm unsure whether the github action should be part of the master branch, since it has no function there and the chosen definition should always be the version in the production branch. But I can include it in the master branch if you want.

**Comment by b-g** [comment]
Thanks! Would want to have just a single source or truth (= the master branch). Hence please merge with master.

**Comment by b-g** [comment]
@PaulRaschke Gave it another try ... failed again :(

<img width="1073" alt="Screen Shot 2020-01-14 at 09 57 36" src="https://user-images.githubusercontent.com/480224/72329494-21118c00-36b5-11ea-9fbd-8994e05bd50c.png">

What creating a Gulp FTP action, test it locally unitil it is 100% and then wrap that into a Github action? Andreas Koller did recently one: https://github.com/andreaskoller/kirby-dev-env/blob/master/gulpfile.js#L54

**Comment by b-g** [comment]
Hi @PaulRaschke! Quick question: Is the FTP issue still in the scope of your HiWi appointment? If not ... no problem ... just let me know. I would give then the Gulp ftp task a try ...

**Comment by PaulRaschke** [comment]
Hi @b-g,
i think I can fix the FTP issue. I will try to fix it asap. I saw that a new version of the [FTP-Deploy-Action](https://github.com/SamKirkland/FTP-Deploy-Action) I used for the Github action has been released, which switched from LFTP to git-ftp as ftp-client. Before I try to fix the problem with the Gulp task, I would try the updated Action as I still prefer it to a Gulp task and it could be implemented faster. But if you prefer the possible solution with Gulp, i will try this first.

**Comment by b-g** [comment]
Hi @PaulRaschke! Website is ready to go! Would like deploy today! :) Should I wait for the new Github action or should I simply use manual FTP? Please let me know. Many thanks + best!

**Comment by PaulRaschke** [comment]
Hi @b-g,
The action is also ready. I missed to notify you, sry. I pushed the new version into the production branch yesterday and the upload worked just fine. Hopefully it's running reliably now 🤞

**Comment by b-g** [comment]
@PaulRaschke Many thanks! Will give it a try! 🤞
