### ISSUE TITLE
Home: OpenMoji Version Number

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#61]
@felixhaeberle 

Please
- load `data/package.json` and get the OpenMoji Version number from there
- strip the ".0" end of the version number. "12.1" is enough and "12.1.0" feels like overkill

**Comment by b-g** [comment]
![2019-12-16 at 13 23](https://user-images.githubusercontent.com/480224/70932442-c3334b00-2007-11ea-95ee-9351b00e5153.jpg)

**Comment by b-g** [comment]
Many thanks! Done with #64.

**Comment by felixhaeberle** [comment]
Ah this could need additional work in case of striping out the version in the markup of the HTML file because on load it can cause weird flashes from the markup (in our case at the moment 12.0) to the real version which then gets replaces by the JS. I'll commit this.

**Comment by felixhaeberle** [comment]
fixed in #67
