### ISSUE TITLE
Add FAQ to navigation

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#66]
@felixhaeberle 

Could you add "FAQ" to the main navigation (external link: https://github.com/hfg-gmuend/openmoji/blob/master/FAQ.md and in between "Samples" and "About")

We get over and over the same questions especially around the license etc. At a later point we might integrate the FAQ into the website ... but as a quick work around the external link is good enough.

**Comment by felixhaeberle** [comment]
Sure! :)

**Comment by felixhaeberle** [comment]
Also deleting the version number in the HTML markup with this pull request for not having the flashing effect when the HTML text gets overridden by JS. 🚀

**Comment by b-g** [comment]
Done
