### ISSUE TITLE
`npm run` does not work on node > 8

### ISSUE THREAD

**Issue by cronin4392** [hfg-gmuend/openmoji-website#7]
Tried installing and starting the repository using node `v10.8.0`. Some errors are thrown during install and also when trying to run `parallelshell` throws some errors. I found [this issue](https://github.com/darkguy2008/parallelshell/issues/57). 

I think an `.nvmrc` file should be added to this repo to specify a version of node that works with the current set up. I tried with `v8.9.1` which seems to work. Also, the readme should be updated to remove the line about using latest version of node.

**Comment by b-g** [comment]
@cronin4392 Many thanks + done as you suggested ✅!
