### ISSUE TITLE
Add "Inkscape Export Instructions" to styleguide

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#71]
Hi @carlinmack! Could you add the "Inkscape Export Instructions" of https://github.com/hfg-gmuend/openmoji/issues/113#issuecomment-576442139 to https://openmoji.org/styleguide/#submission?

**Comment by carlinmack** [comment]
I'll hope to do this monday

**Comment by carlinmack** [comment]
done 30e8879

**Comment by b-g** [comment]
@carlinmack Many thanks! Great to have them ... to show that Illustrator is not the only tool!
