### ISSUE TITLE
Mobile: More descriptive subpage titles

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#75]
"old bullet point 3"

> Not sure. Do you want to stripe out the normal headings of the pages then and display the pages name in the heading then?

> What about a "←" (back arrow) + "Subpage Title"? I would find it better to have the title of the subpage in the header instead of a pretty redundant OpenMoji all the time.

> This could be implemented, should we therefore take the pages name e.g. "Participate" or "Samples" for this? with a back arrow ? pointing to the start page? or the previous page (more complicated).

Yes. Take the page names e.g. "Participate" or "Samples" and add an arrow icon. Link could either bring you back to the last page or home. Both is fine. Pick the easier one in terms of effort.

**Comment by b-g** [comment]
Hi @felixhaeberle! Ping! :) Could you do the last push so that the mobile website can go finally online? Would be so nice ... please!

**Comment by felixhaeberle** [comment]
@b-g Sure, currently I'm in 🇻🇳 and not available for coding, but will be the first thing to do when getting back on 2th of March.
Happy and excited to finally bring this online! 👏
Also, I have plans to extend the emoji site with the emoji mashup bot done by one of our IoT students this semester. Let's then discuss that if and how that could fit in the site in a separate issue! 💪

Thanks again for your patience! 🙏

**Comment by b-g** [comment]
@felixhaeberle Great! Happy holidays in Vietnam! Ping me once you are back in DE! Not aware of the mash up bot ... sounds interesting! :) Best, B

**Comment by b-g** [comment]
@felixhaeberle Ping! :) 🛬 safe and sound in DE? Would be super to get this out before the new semester starts ...

**Comment by felixhaeberle** [comment]
Thanks, yes, save back home, fighting jetlag 😄
Will start asap, today or tomorrow! 👍

**Comment by felixhaeberle** [comment]
@b-g hey! I'm back at it and planning on how to do this! So basically there is 1 problem to solve: we have a page "Participate" (-> /styleguide however 😄) and there we have the headline "Designer? Developer? Love Open Source? Everyone Can Participate!", so I suggest setting a `data-headline` attribute on the headline tag to get the data for the labeling of the menu bar. 

Do you agree with this approach? I'll then also provide the back link to the previous site using `document.referrer` and/or `history.back()`. Or without the back arrow? Ppl on smartphones often use the native back icon in their browsers. You decide!:)

**Comment by b-g** [comment]
@felixhaeberle 
1. data-headline "Participate" is fine
2. No strong preferences either, go with the one with the most minimal effort. We can also get rid of the back arrow and check how it feels.
