### ISSUE TITLE
No high-res "Favicon"?

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#89]
Tiny detail :) @felixhaeberle 

![Screenshot 2020-03-22 at 09 09 15](https://user-images.githubusercontent.com/480224/77294070-db3ff800-6ce3-11ea-93da-4a1bbfcacb3c.png)

**Comment by carlinmack** [comment]
I _**highly**_ recommend https://realfavicongenerator.net generates the files for all platforms and resolutions and doesn't require attribution :)

**Comment by felixhaeberle** [comment]
@b-g I know we have favicons in place but don't know how they reflect the current implementation in browsers, the favicon env is really fast-moving 😅 I'm going to check our favicons with the tool @carlinmack mentioned, I also use this tool in all my projects – there is also a gulp preprocess alternative to the web based engine! :)

**Comment by carlinmack** [comment]
You can check how our favicons currently look with their other tool https://realfavicongenerator.net/favicon_checker

**Comment by felixhaeberle** [comment]
@carlinmack Thanks for the suggestion! I just did that and it's all green 😄 
Meanwhile I imported a new batch of favicons generated by RFG, hopefully that works! :)

**Comment by b-g** [comment]
Will close and re-open if id doesn't get better.
