### ISSUE TITLE
v2.0 discussion

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#9]
**1**
- [x] Lazy load all images and svgs http://jquery.eisbehr.de/lazy/
- [x] Prepare/add updated [data](https://github.com/hfg-gmuend/openmoji/blob/v1.5/data/openmoji.json) and latest emoji of OpenMoji [v1.5](https://github.com/hfg-gmuend/openmoji/tree/v1.5) dev branch
- [x] Add a skintones feature to the emoji detail modal
- [x] Sorting default should be according to Unicode
- [x] Sorting feature by contribution data
- [x] Reflect categories "extras-openmoji" and "extras-unicode" in lirbary side nav ("HfG" has been removed)
- [ ] Scroll anchor bug (cc @Sam0711er can you report plz here)

**2**
* Optimize for mobile 
* More love for the general design of the site

cc @johannawe

**Comment by b-g** [comment]
@PaulRaschke Ping :) FYI: Updated all svgs, pngs and data files in [branch v1.5](https://github.com/hfg-gmuend/openmoji/tree/v1.5). We should see very little changes for 1.5. or even 2.0. Please update those files in this repo / the OpenMoji website. Thanks.

**Comment by b-g** [comment]
Hi @PaulRaschke, Hope all is going well! Ping :) Any news / progress on the OpenMoji Website?

**Comment by PaulRaschke** [comment]
Hi @b-g,
sorry for the late response.
I currently have little time on my hand. I'm confident that I push the changes next weekend at the latest. I just need to review the code. I implemented everything you mentioned for version 1 except the scroll anchor bug. Sadly I didn't have enough time to work on version 2.

**Comment by b-g** [comment]
Hi @PaulRaschke, 

Many thanks for the feedback! Great! Let me know once I should do a review ... 

> Sadly I didn't have enough time to work on version 2.

So does this mean, that you don't have time now or that you won't have time for it in the weeks to come? :)

**Comment by PaulRaschke** [comment]
Hi @b-g,

I just pushed the changes i made.
I don't think that I have enough time in the coming weeks to work on version 2, sorry. I assume it's a rather big task.

**Comment by b-g** [comment]
Hi @PaulRaschke,

many thanks for this! 

Could please quickly also check off the todos in this issue https://github.com/hfg-gmuend/openmoji-website/issues/9#issue-387380472 for maximum transparency?

Do you know another student who might be interested to continue?

**Comment by PaulRaschke** [comment]
I can't think of anyone spontaneously. But I will tell you if someone comes into my mind.

**Comment by b-g** [comment]
@PaulRaschke Many thanks! The new features are great! The skintone selector and the new sorting is very nice! 🙏!!
