### ISSUE TITLE
Emoji detail view (mobile): previous emoji button not aligned 

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/openmoji-website#97]
![Screenshot 2020-03-29 at 20 21 07](https://user-images.githubusercontent.com/480224/77911003-62ffa680-7290-11ea-8f72-2bee95587f29.png)

**Comment by felixhaeberle** [comment]
I fixed this one in #100 aswell :) 👍

**Comment by b-g** [comment]
Fixed! Thanks!
